/**
 * @module LocalPairClient
 * @description REST helpers for the local-first pair flow used by
 * the Add-a-Node card. Hits the agent's existing
 * ``/api/pairing/info`` and ``/api/pairing/claim`` endpoints
 * directly over LAN. No Convex round-trip.
 *
 * The agent treats the act of being on the same LAN as the auth
 * boundary for these two routes — claim only works while the agent
 * is unpaired, and the returned API key is what the GCS uses for
 * every subsequent call.
 * @license GPL-3.0-only
 */

import { getBrowserId } from "@/stores/browser-identity-store";

export interface ProbeResult {
  deviceId: string;
  name: string;
  version: string;
  board: string;
  paired: boolean;
  pairingCode?: string;
  ownerId?: string;
  pairedAt?: number;
  mdnsHost: string;
  profile: "drone" | "ground-station" | "compute" | "lite";
  role?: "direct" | "relay" | "receiver" | null;
  /** The normalised base URL the GCS should keep talking to. */
  hostname: string;
}

export interface ClaimResult {
  apiKey: string;
  deviceId: string;
  name: string;
  mdnsHost: string;
  hostname: string;
}

/** Strip trailing slashes and normalise a user-pasted host string.
 * Bare hostnames default to ``http://<host>:8080``. https URLs are
 * left untouched (TLS endpoints terminate on their own port).
 */
export function normaliseHost(input: string): string {
  let s = input.trim();
  if (!s) return s;
  // Bare hostname → assume http://<host>:8080.
  if (!/^https?:\/\//i.test(s)) {
    s = `http://${s}`;
  }
  // Append :8080 only for http URLs without an explicit port. Leave
  // https alone — TLS endpoints set their own port and 8080 would be
  // wrong 99% of the time.
  try {
    const u = new URL(s);
    if (!u.port && u.protocol === "http:") {
      u.port = "8080";
    }
    // Drop trailing slash from pathname.
    u.pathname = u.pathname.replace(/\/+$/, "");
    return u.toString().replace(/\/+$/, "");
  } catch {
    return s.replace(/\/+$/, "");
  }
}

const FETCH_TIMEOUT_MS = 8000;

/** When the GCS is loaded over HTTPS the browser blocks direct
 * `fetch(http://groundnode.local:8080/...)` calls. We bridge by
 * routing the three pair-flow calls through Mission Control's own
 * Next.js server (`/api/lan-pair/*`), which performs the HTTP
 * request server-side. The server-side proxy enforces the same
 * private-address whitelist via `host-validation.ts` so this
 * doesn't widen the attack surface beyond what the operator could
 * already do from a local terminal.
 *
 * On HTTP origins (Electron at `http://127.0.0.1`, dev at
 * `http://localhost:4000`, or a self-hosted HTTP build), the
 * proxy is unnecessary and we fall back to the direct fetch
 * shape so the pair flow stays a single round-trip.
 */
function shouldUseProxy(): boolean {
  return (
    typeof window !== "undefined" &&
    window.location.protocol === "https:"
  );
}

/** Combine an optional caller signal with a local timeout signal. */
function combineSignals(
  caller?: AbortSignal,
  timeoutMs: number = FETCH_TIMEOUT_MS,
): AbortSignal {
  const timeout = AbortSignal.timeout(timeoutMs);
  if (!caller) return timeout;
  if ("any" in AbortSignal && typeof AbortSignal.any === "function") {
    return AbortSignal.any([caller, timeout]);
  }
  // Fallback for environments without AbortSignal.any.
  const ctrl = new AbortController();
  const onAbort = () => ctrl.abort();
  caller.addEventListener("abort", onAbort);
  timeout.addEventListener("abort", onAbort);
  return ctrl.signal;
}

/** Pair codes use the agent's safe charset (uppercase letters and
 *  digits, with 0/O/1/I/L removed for readability). A 6-char input
 *  matching this regex is unambiguously a code; anything else is a
 *  hostname. The disjoint character sets keep auto-detection clean.
 */
const PAIR_CODE_RE = /^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{6}$/;

export function looksLikePairCode(input: string): boolean {
  return PAIR_CODE_RE.test(input.trim().toUpperCase());
}

/** Result shape mirrored from the agent's beacon registration in
 *  Convex. Used by `probeByCode` to resolve a 6-char code to the
 *  agent's LAN hostname. The apiKey here is the beacon-time key the
 *  agent published — NOT the durable key. The durable key is
 *  generated by the agent's `/api/pairing/claim` on the actual claim
 *  call, which `probeByCode` chains into through `probeAgent` →
 *  `pairLocally`. The beacon key is discarded.
 */
export interface CodeClaimResult {
  deviceId: string;
  name: string;
  apiKey: string;
  mdnsHost?: string;
  localIp?: string;
  board?: string;
  agentVersion?: string;
}

/** Anonymous code-pair: resolve a 6-character pair code via the
 *  Convex anon mutation, then chain into the normal hostname-probe
 *  flow. The Convex round-trip is purely a discovery step — it tells
 *  us the agent's mDNS host or local IP without the operator typing
 *  it. After that the regular `probeAgent` (HTTPS-aware, proxied
 *  through `/api/lan-pair/probe` when needed) does the live ID check,
 *  and the downstream `pairLocally` writes the durable apiKey.
 *
 *  No Convex account required for the discovery step. Mixed-content
 *  safe (Convex over HTTPS, then the LAN proxy for the agent call).
 */
export async function probeByCode(
  rawCode: string,
  claimAnon: (args: {
    code: string;
    browserUserId: string;
  }) => Promise<CodeClaimResult>,
  signal?: AbortSignal,
): Promise<ProbeResult> {
  const cleaned = rawCode.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!PAIR_CODE_RE.test(cleaned)) {
    throw new PairClientError(
      "badCodeError",
      "Pair code must be six characters (letters and digits).",
    );
  }
  const lookup = await claimAnon({
    code: cleaned,
    browserUserId: getBrowserId(),
  });
  // The server-side LAN proxy (used on HTTPS) runs inside a
  // container that doesn't speak mDNS — Node's default resolver
  // can't translate `*.local`. Prefer the local IP when we'll go
  // through the proxy; prefer the mDNS hostname when the browser
  // is dialling directly (HTTP / Electron / dev) so an IP
  // renumber after DHCP doesn't kill a future session.
  const hostFrom = shouldUseProxy()
    ? lookup.localIp || lookup.mdnsHost || ""
    : lookup.mdnsHost || lookup.localIp || "";
  if (!hostFrom) {
    throw new PairClientError(
      "codeNoHostError",
      "Pair code is valid but the agent hasn't advertised a network address yet. Wait a few seconds and try again.",
    );
  }
  // Chain into the regular probe so the live agent ID, profile, role
  // and version come from the agent itself, not the cached beacon
  // entry. Goes through the LAN proxy on HTTPS automatically.
  return probeAgent(hostFrom, signal);
}

/** Hit ``/api/pairing/info`` and return the agent identity.
 * Times out after 8s so a non-responsive host doesn't hang the UI.
 *
 * Cross-protocol path: when the GCS is on HTTPS, the request goes
 * through Mission Control's own `/api/lan-pair/probe` route, which
 * forwards the HTTP request to the LAN agent server-side. On HTTP
 * origins the direct fetch is preferred so the pair stays a single
 * round-trip.
 */
export async function probeAgent(
  rawHost: string,
  signal?: AbortSignal,
): Promise<ProbeResult> {
  const host = normaliseHost(rawHost);
  if (!host) {
    throw new PairClientError("enterHostnameError", "Enter a hostname or URL to probe");
  }
  let body: Record<string, unknown>;
  if (shouldUseProxy()) {
    const resp = await fetch(`/api/lan-pair/probe`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({ host }),
      signal: combineSignals(signal),
    });
    if (!resp.ok) {
      const parsed = (await safeJson(resp)) as
        | { error?: string; message?: string }
        | null;
      throw new PairClientError(
        parsed?.error === "host_not_private"
          ? "hostNotPrivateError"
          : "probeFailedStatusError",
        parsed?.message ?? `Probe failed: ${resp.status} ${resp.statusText}`,
        { status: resp.status, statusText: resp.statusText },
      );
    }
    body = (await resp.json()) as Record<string, unknown>;
  } else {
    const resp = await fetch(`${host}/api/pairing/info`, {
      method: "GET",
      headers: { Accept: "application/json" },
      signal: combineSignals(signal),
    });
    if (!resp.ok) {
      throw new PairClientError(
        "probeFailedStatusError",
        `Probe failed: ${resp.status} ${resp.statusText}`,
        { status: resp.status, statusText: resp.statusText },
      );
    }
    body = (await resp.json()) as Record<string, unknown>;
  }
  const deviceId = String(body.device_id ?? "");
  if (!deviceId) {
    throw new PairClientError("missingDeviceIdError", "Probe response missing device_id");
  }
  const profile = (body.profile as string) || "drone";
  const role = (body.role as string | undefined) ?? null;
  return {
    deviceId,
    name: String(body.name ?? "ADOS Agent"),
    version: String(body.version ?? ""),
    board: String(body.board ?? "unknown"),
    paired: Boolean(body.paired),
    pairingCode: (body.pairing_code as string | undefined) ?? undefined,
    ownerId: (body.owner_id as string | undefined) ?? undefined,
    pairedAt: (body.paired_at as number | undefined) ?? undefined,
    mdnsHost: String(body.mdns_host ?? ""),
    profile: profile as ProbeResult["profile"],
    role: role as ProbeResult["role"],
    hostname: host,
  };
}

async function safeJson(resp: Response): Promise<unknown> {
  try {
    return await resp.json();
  } catch {
    return null;
  }
}

export class AgentAlreadyPairedError extends Error {
  constructor(message?: string) {
    super(message || "Agent is already paired. Unpair from the agent first.");
    this.name = "AgentAlreadyPairedError";
  }
}

/** Structured error class for pair-client failures. The ``code``
 * field maps to an i18n key under ``command.addNode.*`` so the
 * consuming component can render a translated message; the
 * ``message`` is kept as a dev-readable fallback. ``details`` is
 * spread into the translation interpolation context, so values are
 * filtered to ``string | number`` at construction. Object-valued
 * fields (which the agent shouldn't return but might in error
 * paths) are stringified to ``[object Object]``-resistant strings
 * via ``JSON.stringify`` so the t() call never blows up. */
export class PairClientError extends Error {
  readonly code: string;
  readonly details: Record<string, string | number>;
  constructor(
    code: string,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = "PairClientError";
    this.code = code;
    const filtered: Record<string, string | number> = {};
    for (const [k, v] of Object.entries(details)) {
      if (typeof v === "string" || typeof v === "number") {
        filtered[k] = v;
      } else if (v == null) {
        filtered[k] = "";
      } else {
        try {
          filtered[k] = JSON.stringify(v);
        } catch {
          filtered[k] = String(v);
        }
      }
    }
    this.details = filtered;
  }
}

/** POST ``/api/pairing/claim`` with the browser-local UUID as ``user_id``.
 * The browser UUID acts as the pair owner id — the agent treats it
 * as the credential for unpair on subsequent requests.
 */
export async function pairLocally(
  rawHost: string,
  signal?: AbortSignal,
): Promise<ClaimResult> {
  const host = normaliseHost(rawHost);
  const userId = getBrowserId();
  const resp = shouldUseProxy()
    ? await fetch(`/api/lan-pair/claim`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify({ host, userId }),
        signal: combineSignals(signal),
      })
    : await fetch(`${host}/api/pairing/claim`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify({ user_id: userId }),
        signal: combineSignals(signal),
      });
  if (resp.status === 409) {
    throw new AgentAlreadyPairedError();
  }
  if (!resp.ok) {
    throw new PairClientError(
      "pairFailedStatusError",
      `Pair failed: ${resp.status} ${resp.statusText}`,
      { status: resp.status, statusText: resp.statusText },
    );
  }
  const body = (await resp.json()) as Record<string, unknown>;
  return {
    apiKey: String(body.api_key ?? ""),
    deviceId: String(body.device_id ?? ""),
    name: String(body.name ?? "ADOS Agent"),
    mdnsHost: String(body.mdns_host ?? ""),
    hostname: host,
  };
}

/** POST ``/api/pairing/unpair`` with the stored API key in the header. */
export async function unpairLocal(
  hostname: string,
  apiKey: string,
  signal?: AbortSignal,
): Promise<void> {
  const host = normaliseHost(hostname);
  const resp = shouldUseProxy()
    ? await fetch(`/api/lan-pair/unpair`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify({ host, apiKey }),
        signal,
      })
    : await fetch(`${host}/api/pairing/unpair`, {
        method: "POST",
        headers: {
          "X-API-Key": apiKey,
          Accept: "application/json",
        },
        signal,
      });
  if (!resp.ok && resp.status !== 409) {
    throw new PairClientError(
      "unpairFailedStatusError",
      `Unpair failed: ${resp.status} ${resp.statusText}`,
      { status: resp.status, statusText: resp.statusText },
    );
  }
}
